//TODO [KAN-104]: complete the documentation of user-related endpoints

// Register a new user (username not present in server/API/users/users.json)
POST http://localhost:3001/users/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Test1",
    "lastName": "User",
    "email": "test.user22@example.com",
    "password": "TestPass123!"
}

###

// Login with an existing user from server/API/users/users.json
// (uses the `migi@inpay.com` account present in the file)
POST http://localhost:3001/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "migi@inpay.com",
    "password": "1234"
}
