
###
// Returns basket for a single user by username
GET http://localhost:3000/user/mia.anderson/basket HTTP/1.1

###
// Returns 404 since the user does not exist - no basket can be found
GET http://localhost:3000/user/wrong.name/basket HTTP/1.1

